

CREATE TABLE IF NOT EXISTS produits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    chemin_image VARCHAR(255) NOT NULL,
    prix DECIMAL(10,2) NOT NULL,
    date_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
